
export const SEND = 'SEND';
export const ADD_SEND_TRANSACTION = 'ADD_SEND_TRANSACTION';
export const ADD_SEND_TRANSACTION_FAILED = 'ADD_TRANSACTION_FAILED';
export const FETCH_SEND_TRANSACTIONS = 'FETCH_SEND_TRANSACTIONS';
export const FETCH_SEND_TRANSACTIONS_FAILED = 'FETCH_SEND_TRANSACTIONS_FAILED';

export const DEPOSIT = 'DEPOSIT';
export const ADD_DEPOSIT_TRANSACTION = 'ADD_DEPOSIT_TRANSACTION';
export const ADD_DEPOSIT_TRANSACTION_FAILED = 'ADD_DEPOSIT_TRANSACTION_FAILED';
export const FETCH_DEPOSIT_TRANSACTIONS = 'FETCH_DEPOSIT_TRANSACTIONS';
export const FETCH_DEPOSIT_TRANSACTIONS_FAILED = 'FETCH_DEPOSIT_TRANSACTIONS_FAILED';


export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';


